### PR TITLE
Upgrade to latest

### PR DESCRIPTION
**Pull request by koivunej**
With https://github.com/rs-ipfs/rust-ipfs/pull/233 things are looking good. All the problematic tests are ignored.

There is still though a hang which I haven't solved. It seems that combination of miscellanious.version and miscellanious.stop cause a hang. Tricky to understand how ... Also those endpoints have timeout tests which may be causing this (some responses take 3ms) so, ignoring those for now.

```
  143 passing (42s)
  25 pending
```

### CODE REVIEW

**Comment by koivunej** [comment]
Do not merge this yet :) I'll handle it.

**Comment by koivunej** [comment]
So we needed to wait for https://github.com/rs-ipfs/rust-ipfs/pull/233 to pass before upgrading. And then we need ... a small PR to make sure things are still ok? Or I'll just do a fake PR with github CI changed to this PR and then close it if it looks good.

**Comment by ljedrz** [comment]
My results with #233:
```
  142 passing (36s)
  25 pending
  1 failing
```

**Comment by ljedrz** [comment]
LGTM

**Comment by koivunej** [comment]
Green light on https://github.com/rs-ipfs/rust-ipfs/pull/234 means we can merge this (dc7f6da) in.

**Pull request merged**
